import type { Metadata } from "next";
import "./globals.css";
import { Footer, Header } from "@/components/shared-components";
export const metadata: Metadata = {
  title: "Food delivary",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  admin,
}: Readonly<{
  children: React.ReactNode;
  admin: React.ReactNode;
}>) {
  let isUser = false;
  return (
    <html lang="en">
      <body>
        {isUser ? (
          <>
            <Header />
            {children}
            <Footer />
          </>
        ) : (
          admin
        )}
      </body>
    </html>
  );
}
